# Generated by Django 5.2.1 on 2025-11-03 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='created by')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='updated by')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='deleted date')),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='deleted by')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
                'db_table': 'species',
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='created by')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='updated by')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='deleted date')),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='deleted by')),
                ('name', models.CharField(max_length=100)),
                ('size_category', models.CharField(choices=[('toy', 'Toy/Enano'), ('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande'), ('gigante', 'Gigante')], max_length=100)),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeds', to='nomenclatures.species')),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
                'db_table': 'breeds',
            },
        ),
    ]
