# Generated by Django 5.2.1 on 2025-11-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0003_area_deleted_breed_deleted_species_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
