# Generated by Django 5.2.1 on 2025-12-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclatures', '0005_alter_area_name_alter_breed_name_alter_species_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='species',
            field=models.CharField(choices=[('canino', 'Canino'), ('felino', 'Felino')], max_length=100, verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='size_category',
            field=models.CharField(choices=[('toy', 'Toy/Enano'), ('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande'), ('gigante', 'Gigante'), ('gato_estandar', 'Gato Estandar')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Species',
        ),
    ]
