# Generated by Django 5.2.1 on 2025-11-30 00:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomenclatures', '0005_alter_area_name_alter_breed_name_alter_species_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='created by')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='updated by')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='deleted date')),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='deleted by')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('carnet', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='El carnet debe tener exactamente 11 dígitos.', regex='^\\d{11}$')], verbose_name='Carnet')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('phone_number', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 8 dígitos.', regex='^\\d{8}$')], verbose_name='Número de teléfono')),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='created by')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='updated by')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='deleted date')),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='deleted by')),
                ('code', models.CharField(editable=False, max_length=8, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('sex', models.CharField(choices=[('macho', 'macho'), ('hembra', 'hembra')], max_length=100, verbose_name='Sexo')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Peso')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('reprod_state', models.CharField(choices=[('vacio', 'vacio'), ('gestante', 'gestante'), ('lactacion', 'lactación')], default='vacio', max_length=100, verbose_name='Estado reproductivo')),
                ('deleted', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='animales/', verbose_name='Imagen')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='nomenclatures.breed', verbose_name='Raza')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='clinic.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
            },
        ),
        migrations.CreateModel(
            name='ClinicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='created by')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='updated by')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='deleted date')),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='deleted by')),
                ('skin_mucosas', models.TextField(blank=True, null=True, verbose_name='Piel y Mucosas')),
                ('respiratory_system', models.TextField(blank=True, null=True, verbose_name='Sistema Respiratorio')),
                ('digestive_system', models.TextField(blank=True, null=True, verbose_name='Sistema Digestivo')),
                ('circulatory_system', models.TextField(blank=True, null=True, verbose_name='Sistema Circulatorio')),
                ('nervous_system', models.TextField(blank=True, null=True, verbose_name='Sistema Nervioso')),
                ('locomotor_system', models.TextField(blank=True, null=True, verbose_name='Sistema Locomotor')),
                ('reproductive_system', models.TextField(blank=True, null=True, verbose_name='Sistema Reproductor')),
                ('pres_clinic_diag', models.TextField(blank=True, null=True, verbose_name='Diagnóstico Clínico Presuntivo')),
                ('treatment', models.TextField(blank=True, null=True, verbose_name='Tratamiento')),
                ('created_date', models.DateTimeField(auto_now_add=True, unique_for_date=True, verbose_name='created date')),
                ('deleted', models.BooleanField(default=False)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_pages', to='clinic.pet', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
            },
        ),
    ]
