# Generated by Django 5.2.1 on 2025-11-30 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
        migrations.AlterModelTable(
            name='clinicpage',
            table='clinic_pages',
        ),
        migrations.AlterModelTable(
            name='pet',
            table='pets',
        ),
    ]
