# Generated by Django 5.2.1 on 2026-01-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_client_table_alter_clinicpage_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicpage',
            options={'verbose_name': 'Hoja Clínica', 'verbose_name_plural': 'Hojas Clínicas'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Mascota', 'verbose_name_plural': 'Mascotas'},
        ),
    ]
